# Generated by Django 5.1.5 on 2026-09-10 00:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('teachers', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Evaluation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'Pendiente'), ('approved', 'Aprobado'), ('rejected', 'Rechazado')], default='pending', max_length=20, verbose_name='estado')),
                ('rating', models.PositiveSmallIntegerField(blank=True, help_text='Puntaje otorgado por la evaluadora.', null=True, verbose_name='evaluación (1-5)')),
                ('notes', models.TextField(blank=True, verbose_name='notas internas')),
                ('evaluated_at', models.DateTimeField(blank=True, null=True, verbose_name='fecha de evaluación')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('evaluated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='evaluations_made', to=settings.AUTH_USER_MODEL, verbose_name='evaluado por')),
                ('profile', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='evaluation', to='teachers.teacherprofile')),
            ],
            options={
                'verbose_name': 'evaluación',
                'verbose_name_plural': 'evaluaciones',
                'ordering': ['-updated_at'],
            },
        ),
    ]
