# Generated by Django 5.1.5 on 2026-09-10 00:29

import django.db.models.deletion
import schools.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='School',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='nombre del colegio')),
                ('rbd', models.CharField(blank=True, help_text='Rol Base de Datos del establecimiento (opcional).', max_length=20, verbose_name='RBD')),
                ('phone', models.CharField(blank=True, max_length=30, verbose_name='teléfono')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('comuna', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='schools', to='catalog.comuna', verbose_name='comuna')),
                ('region', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='schools', to='catalog.region', verbose_name='región')),
            ],
            options={
                'verbose_name': 'colegio',
                'verbose_name_plural': 'colegios',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='SchoolInvitation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, verbose_name='email invitado')),
                ('token', models.CharField(default=schools.models._new_token, editable=False, max_length=64, unique=True)),
                ('accepted', models.BooleanField(default=False, verbose_name='aceptada')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('invited_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='invitations_sent', to=settings.AUTH_USER_MODEL)),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invitations', to='schools.school')),
            ],
            options={
                'verbose_name': 'invitación',
                'verbose_name_plural': 'invitaciones',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SchoolMembership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('school_role', models.CharField(choices=[('owner', 'Administrador del colegio'), ('member', 'Miembro')], default='member', max_length=20, verbose_name='rol en el colegio')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to='schools.school')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='school_memberships', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'miembro de colegio',
                'verbose_name_plural': 'miembros de colegio',
                'unique_together': {('school', 'user')},
            },
        ),
    ]
