# Generated by Django 5.1.5 on 2026-09-10 00:29

import django.db.models.deletion
import teachers.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TeacherProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=200, verbose_name='nombre completo')),
                ('phone', models.CharField(blank=True, max_length=30, verbose_name='teléfono de contacto')),
                ('contact_email', models.EmailField(blank=True, max_length=254, verbose_name='email de contacto')),
                ('birth_date', models.DateField(blank=True, null=True, verbose_name='fecha de nacimiento')),
                ('bio', models.TextField(blank=True, help_text='Cuéntale al colegio sobre tu experiencia.', verbose_name='presentación')),
                ('is_bilingual', models.BooleanField(default=False, verbose_name='bilingüe')),
                ('languages', models.CharField(blank=True, help_text='Ej: Inglés (avanzado), Francés (intermedio).', max_length=200, verbose_name='idiomas')),
                ('available_short', models.BooleanField(default=True, verbose_name='reemplazos cortos (días/semanas)')),
                ('available_long', models.BooleanField(default=True, verbose_name='reemplazos largos (meses)')),
                ('available_mon', models.BooleanField(default=True, verbose_name='lunes')),
                ('available_tue', models.BooleanField(default=True, verbose_name='martes')),
                ('available_wed', models.BooleanField(default=True, verbose_name='miércoles')),
                ('available_thu', models.BooleanField(default=True, verbose_name='jueves')),
                ('available_fri', models.BooleanField(default=True, verbose_name='viernes')),
                ('available_from', models.DateField(blank=True, null=True, verbose_name='disponible desde')),
                ('availability_notes', models.CharField(blank=True, max_length=300, verbose_name='notas de disponibilidad')),
                ('is_active', models.BooleanField(default=True, help_text='Desactívalo si por ahora no quieres aparecer para los colegios.', verbose_name='perfil activo')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('comuna', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='teachers', to='catalog.comuna', verbose_name='comuna de residencia')),
                ('preferred_comunas', models.ManyToManyField(blank=True, related_name='preferred_by_teachers', to='catalog.comuna', verbose_name='comunas donde prefiero trabajar')),
                ('region', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='teachers', to='catalog.region', verbose_name='región de residencia')),
                ('subjects', models.ManyToManyField(blank=True, related_name='teachers', to='catalog.subject', verbose_name='asignaturas que puedo cubrir')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='teacher_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'perfil de profe',
                'verbose_name_plural': 'perfiles de profes',
            },
        ),
        migrations.CreateModel(
            name='Certificate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('doc_type', models.CharField(choices=[('titulo', 'Título profesional'), ('antecedentes', 'Certificado de antecedentes'), ('diploma', 'Diploma / postítulo'), ('cv', 'Currículum'), ('otro', 'Otro')], default='titulo', max_length=20, verbose_name='tipo de documento')),
                ('name', models.CharField(max_length=200, verbose_name='nombre del documento')),
                ('file', models.FileField(upload_to=teachers.models.certificate_upload_path, verbose_name='archivo')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='certificates', to='teachers.teacherprofile')),
            ],
            options={
                'verbose_name': 'certificado',
                'verbose_name_plural': 'certificados',
                'ordering': ['-uploaded_at'],
            },
        ),
    ]
